server:
  servlet:
    context-path: /hello-config-client
  port: 9091
  
# Spring application properties
spring:
  application:
    name: HelloService
  profiles:
    active: pre
  
  # 1. Agregar dependencias para Spring Cloud Bus
  # 2. Agregar configuración para RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: '{cipher}db9f2d1ed692393082da9f59820921d23d1a87b77334efaf3f24b87712a27374'

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,bus-env

hello:
  message: Hi hello service pre from git! (changed!)

guest: '{cipher}db9f2d1ed692393082da9f59820921d23d1a87b77334efaf3f24b87712a27374'
