server:
  servlet:
    context-path: /users-config-client
  port: 9091
  
# Spring application properties
spring:
  application:
    name: UsersService
  profiles:
    active: dev
  
  # 1. Agregar dependencias para Spring Cloud Bus
  # 2. Agregar configuración para RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: '{cipher}db9f2d1ed692393082da9f59820921d23d1a87b77334efaf3f24b87712a27374'

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,bus-env

hello:
  message: Hi users service dev from git!

guest: '{cipher}db9f2d1ed692393082da9f59820921d23d1a87b77334efaf3f24b87712a27374'
